In [17]:
import pandas as pd
import re
import os

# **| Separación del Dataset Grecia**

In [18]:
#Cargar desde un archivo .csv
df = pd.read_csv('Grecia.csv')
Grecia = df.drop(['Unnamed: 0'], axis=1)

Grecia.head()

,last_scraped,source,name,description,neighborhood_overview,host_name,host_since,host_location,host_about,host_response_time,...,availability_365,number_of_reviews,number_of_reviews_l30d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
0,2024-09-23,city scrape,"3 bedrooms, 2 bathrooms, 2nd floor with elevator",The apartment is 3-bedroom apartment with 2-ba...,Ampelokipi district is nice multinational and ...,Emmanouil,2009-09-08,"Athens, Greece",Athens Quality Apartments is a company started...,within an hour,...,340,53.0,0.0,4.87,4.89,4.85,4.91,4.58,4.75,0.33
1,2024-09-23,city scrape,Athens Quality Apartments - Deluxe Apartment,Athens Quality Apartments - Deluxe apartment i...,Ampelokipi district is nice multinational and ...,Emmanouil,2009-09-08,"Athens, Greece",Athens Quality Apartments is a company started...,within an hour,...,350,82.0,0.0,4.83,4.85,4.85,4.90,4.80,4.75,0.56
2,2024-09-23,city scrape,Athens Quality Apartments - Studio,The Studio is an <br />-excellent located <br ...,Ampelokipi district is nice multinational and ...,Emmanouil,2009-09-08,"Athens, Greece",Athens Quality Apartments is a company started...,within an hour,...,341,107.0,0.0,4.85,4.92,4.93,4.97,4.79,4.78,0.73
3,2024-09-23,city scrape,"AQA-No2 1-bedroom, smart tv, fiber connection,","AQA No2 is 1-bedroom apartment (47m2), on the ...",Ampelokipi district is nice multinational and ...,Emmanouil,2009-09-08,"Athens, Greece",Athens Quality Apartments is a company started...,within an hour,...,350,36.0,0.0,4.83,4.97,4.91,4.89,4.82,4.82,0.21
4,2024-09-23,city scrape,"AQA-No7, Great mattress, high speed internet",THE MATTRESS - KING KOIL - Camden Luxury 160x2...,No disponible,Emmanouil,2009-09-08,"Athens, Greece",Athens Quality Apartments is a company started...,within an hour,...,358,25.0,0.0,4.84,4.88,4.96,4.96,4.75,4.71,0.17

In [19]:
# Separar los datos en diferentes datasets basados en el valor de "room_type"
room_type_groups = Grecia.groupby('room_type')

# Crear un diccionario para almacenar los datasets separados
room_type_datasets = {room_type: data for room_type, data in room_type_groups}

# Mostrar los nombres de los datasets creados
room_type_datasets.keys()

dict_keys(['Entire home/apt', 'Hotel room', 'Private room', 'Shared room'])

In [20]:
for room_type, data in room_type_datasets.items():
    print(f"Dataset: {room_type}")
    display(data.head())

Dataset: Entire home/apt

,last_scraped,source,name,description,neighborhood_overview,host_name,host_since,host_location,host_about,host_response_time,...,availability_365,number_of_reviews,number_of_reviews_l30d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
0,2024-09-23,city scrape,"3 bedrooms, 2 bathrooms, 2nd floor with elevator",The apartment is 3-bedroom apartment with 2-ba...,Ampelokipi district is nice multinational and ...,Emmanouil,2009-09-08,"Athens, Greece",Athens Quality Apartments is a company started...,within an hour,...,340,53.0,0.0,4.87,4.89,4.85,4.91,4.58,4.75,0.33
1,2024-09-23,city scrape,Athens Quality Apartments - Deluxe Apartment,Athens Quality Apartments - Deluxe apartment i...,Ampelokipi district is nice multinational and ...,Emmanouil,2009-09-08,"Athens, Greece",Athens Quality Apartments is a company started...,within an hour,...,350,82.0,0.0,4.83,4.85,4.85,4.90,4.80,4.75,0.56
2,2024-09-23,city scrape,Athens Quality Apartments - Studio,The Studio is an <br />-excellent located <br ...,Ampelokipi district is nice multinational and ...,Emmanouil,2009-09-08,"Athens, Greece",Athens Quality Apartments is a company started...,within an hour,...,341,107.0,0.0,4.85,4.92,4.93,4.97,4.79,4.78,0.73
3,2024-09-23,city scrape,"AQA-No2 1-bedroom, smart tv, fiber connection,","AQA No2 is 1-bedroom apartment (47m2), on the ...",Ampelokipi district is nice multinational and ...,Emmanouil,2009-09-08,"Athens, Greece",Athens Quality Apartments is a company started...,within an hour,...,350,36.0,0.0,4.83,4.97,4.91,4.89,4.82,4.82,0.21
4,2024-09-23,city scrape,"AQA-No7, Great mattress, high speed internet",THE MATTRESS - KING KOIL - Camden Luxury 160x2...,No disponible,Emmanouil,2009-09-08,"Athens, Greece",Athens Quality Apartments is a company started...,within an hour,...,358,25.0,0.0,4.84,4.88,4.96,4.96,4.75,4.71,0.17

Dataset: Hotel room

,last_scraped,source,name,description,neighborhood_overview,host_name,host_since,host_location,host_about,host_response_time,...,availability_365,number_of_reviews,number_of_reviews_l30d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
746,2024-09-23,previous scrape,Standard Double Room with private shower & Bal...,"My place is close to restaurants and dining, p...",No disponible,Konstantinos,2016-01-10,"Athens, Greece",No disponible,within an hour,...,320,1.0,0.0,4.00,5.00,5.00,5.00,5.00,5.00,0.01
825,2024-09-23,city scrape,Triple Room with private shower & Balcony,"My place is close to restaurants and dining, p...",No disponible,Konstantinos,2016-01-10,"Athens, Greece",No disponible,within an hour,...,328,1.0,0.0,5.00,5.00,5.00,5.00,5.00,5.00,0.03
1333,2024-09-23,city scrape,Exceptional Penthouse close to Acropolis by GHH,This exceptional Penthouse close to the Acropo...,A formerly low-profile neighborhood at the foo...,Golden Home Holidays,2015-10-20,"Athens, Greece","Find your own home in Greece, for holidays or ...",within an hour,...,135,84.0,1.0,4.64,4.73,4.73,4.94,4.95,4.69,1.03
1455,2024-09-23,city scrape,"Acropolis Grand Residence, Stunning Views","Located in a 1930’s neoclassical building, dir...",The residence is located at 12 Syggrou avenue ...,Vasileios,2017-01-31,"Athens, Greece",We are Bill & John two young entrepreneurs wit...,within an hour,...,292,184.0,1.0,4.98,4.97,4.97,4.98,4.99,4.95,2.33
1458,2024-09-23,city scrape,AcropolisView -Two Bedroom Apt by Meros,The apartment is located at the foothills of A...,Thissio is a traditional neighborhood in downt...,Meros,2015-05-06,"Athens, Greece","Hi, we are Meros team and we will be your host...",within an hour,...,74,116.0,5.0,4.77,4.84,4.88,4.79,4.92,4.79,1.48

Dataset: Private room

,last_scraped,source,name,description,neighborhood_overview,host_name,host_since,host_location,host_about,host_response_time,...,availability_365,number_of_reviews,number_of_reviews_l30d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
44,2024-09-23,city scrape,Lovely room in historic center,"relaxed, quiet area, next to all historic and ...",No disponible,Haris,2012-06-03,"Athens, Greece",Welcome in my profile on Airbnb! Infos about o...,within an hour,...,83,4.0,0.0,4.75,4.75,4.50,4.50,4.75,4.50,0.03
119,2024-09-23,city scrape,Room and private bathroom in Athens,Comfortable and quiet private bedroom with a k...,In my safe and easily accessible neighborhood ...,Nick,2014-04-06,"Athens, Greece","Hey , I'm Nick!",within an hour,...,29,42.9,5.0,4.92,4.97,4.91,4.96,4.87,4.93,3.09
123,2024-09-23,city scrape,Room with Balcony in Filopapos Hill,No disponible,No disponible,Sofia,2013-06-19,"Athens, Greece",I like traveling all over the world. It makes ...,a few days or more,...,362,15.0,0.0,4.73,4.87,5.00,5.00,4.73,4.80,0.11
131,2024-09-23,city scrape,Room with privet bathroom in Athens,Comfortable and quiet private bedroom with a p...,In my safe and easily accessible neighborhood ...,Nick,2014-04-06,"Athens, Greece","Hey , I'm Nick!",within an hour,...,52,42.9,3.0,4.93,4.95,4.96,4.95,4.87,4.94,3.08
149,2024-09-23,city scrape,Acropolis view-150 metres from Metro Monastiraki!,"My house is located in Monastiraki area, righ...",My neighborhood is the most charming area in A...,Makis,2014-05-06,"Athens, Greece",I am an actor and director. I like writing and...,within an hour,...,0,189.0,0.0,4.59,4.74,4.54,4.79,4.90,4.61,1.50

Dataset: Shared room

,last_scraped,source,name,description,neighborhood_overview,host_name,host_since,host_location,host_about,host_response_time,...,availability_365,number_of_reviews,number_of_reviews_l30d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
2091,2024-09-23,city scrape,Bedway Athens Hostel (Bed in female dormitory),"Bedway Athens Hostel is a brand new, modern Ho...",No disponible,Bedway Athens,2018-08-27,"Athens, Greece",No disponible,within a day,...,335,14.0,0.0,4.21,4.50,4.21,4.50,4.71,4.57,0.19
2125,2024-09-23,city scrape,Bedway Athens Hostel (Bed in mixed dormitory),"Bedway Athens Hostel is a brand new, modern Ho...",No disponible,Bedway Athens,2018-08-27,"Athens, Greece",No disponible,within a day,...,174,33.0,1.0,4.70,4.61,4.55,4.76,4.82,4.88,0.45
2133,2024-09-23,city scrape,Bedway Athens Hostel (Bed in mixed dormitory),"Bedway Athens Hostel is a brand new, modern Ho...",No disponible,Bedway Athens,2018-08-27,"Athens, Greece",No disponible,within a day,...,171,35.0,0.0,4.40,4.60,4.43,4.57,4.51,4.60,0.61
2134,2024-09-23,city scrape,Bedway Athens Hostel (Bed in mixed dormitory),"Bedway Athens Hostel is a brand new, modern Ho...",No disponible,Bedway Athens,2018-08-27,"Athens, Greece",No disponible,within a day,...,179,8.0,0.0,3.88,3.88,3.88,4.90,3.88,3.88,0.20
2135,2024-09-23,city scrape,Bedway Athens Hostel (Bed in female dormitory),"Bedway Athens Hostel is a brand new, modern Ho...",No disponible,Bedway Athens,2018-08-27,"Athens, Greece",No disponible,within a day,...,179,1.0,0.0,4.00,5.00,4.80,5.00,5.00,4.00,0.02

In [21]:
# Crear la carpeta del país si no existe
pais = 'Grecia'
carpeta_pais = f"room_type_{pais}"
os.makedirs(carpeta_pais, exist_ok=True)

for room_type, data in room_type_datasets.items():
    # Limpiar el nombre del archivo (eliminar caracteres problemáticos y reemplazar espacios)
    sanitized_name = re.sub(r'[^\w\s]', '', room_type).replace(' ', '_')
    
    # Construir la ruta del archivo dentro de la carpeta del país
    filename = os.path.join(carpeta_pais, f"{sanitized_name}_{pais}.csv")
    
    # Guardar el dataset en un archivo CSV
    data.to_csv(filename, index=False)

    print(f"Archivo guardado en: {filename}")

Archivo guardado en: room_type_Grecia\Entire_homeapt_Grecia.csv
Archivo guardado en: room_type_Grecia\Hotel_room_Grecia.csv
Archivo guardado en: room_type_Grecia\Private_room_Grecia.csv
Archivo guardado en: room_type_Grecia\Shared_room_Grecia.csv

# **| Separación del Dataset México**

In [22]:
#Cargar desde un archivo .csv
df = pd.read_csv('México.csv')
Mexico = df.drop(['Unnamed: 0'], axis=1)

Mexico.head()

,last_scraped,source,name,description,neighborhood_overview,host_name,host_since,host_location,host_about,host_response_time,...,availability_365,number_of_reviews,number_of_reviews_l30d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
0,2024-09-25,city scrape,Villa Dante,"Dentro de Villa un estudio de arte con futon, ...","Santa Fe Mall, Interloma Park and the Lion Des...",Dici,2010-06-28,2010-06-28,"Master in visual arts, film photography & Mark...",a few days or more,...,363,0.0,0.0,4.80,4.90,4.80,4.80,4.80,4.70,1.70
1,2024-09-26,previous scrape,Condesa Haus,A new concept of hosting in mexico through a b...,Información acerca del vecindario no proporcio...,Fernando,2010-08-09,2010-08-09,Condesa Haus offers independent studios and ...,within an hour,...,325,64.0,0.0,4.58,4.56,4.70,4.78,4.98,4.48,0.41
2,2024-09-26,city scrape,"2 bedroom apt. deco bldg, Condesa","Comfortably furnished, sunny, 2 bedroom apt., ...",Información acerca del vecindario no proporcio...,Nicholas,2011-01-04,2011-01-04,"I am a journalist writing about food, (book an...",within an hour,...,325,49.0,0.0,4.90,4.81,4.75,4.92,4.98,4.91,0.31
3,2024-09-25,city scrape,Beautiful light Studio Coyoacan- full equipped !,COYOACAN designer studio quiet & safe! well eq...,Coyoacan is a beautiful neighborhood famous fo...,Trisha,2010-08-24,2010-08-24,"I am a mother, documentary film maker and phot...",within a few hours,...,257,127.0,2.0,4.91,4.90,4.96,4.98,4.96,4.92,0.83
4,2024-09-25,city scrape,NEW DESIGNER LOFT,Is the best ever place triple L <br />Location...,"Is located in the best area of Mexico City, Po...",Andrea,2011-04-27,2011-04-27,I Leave in Mexico City... I am an Architect an...,within an hour,...,275,11.0,0.0,4.91,5.00,5.00,4.73,4.91,4.82,0.11

In [23]:
# Separar los datos en diferentes datasets basados en el valor de "room_type"
room_type_groups = Grecia.groupby('room_type')

# Crear un diccionario para almacenar los datasets separados
room_type_datasets = {room_type: data for room_type, data in room_type_groups}

# Mostrar los nombres de los datasets creados
room_type_datasets.keys()

dict_keys(['Entire home/apt', 'Hotel room', 'Private room', 'Shared room'])

In [24]:
for room_type, data in room_type_datasets.items():
    print(f"Dataset: {room_type}")
    display(data.head())

Dataset: Entire home/apt

,last_scraped,source,name,description,neighborhood_overview,host_name,host_since,host_location,host_about,host_response_time,...,availability_365,number_of_reviews,number_of_reviews_l30d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
0,2024-09-23,city scrape,"3 bedrooms, 2 bathrooms, 2nd floor with elevator",The apartment is 3-bedroom apartment with 2-ba...,Ampelokipi district is nice multinational and ...,Emmanouil,2009-09-08,"Athens, Greece",Athens Quality Apartments is a company started...,within an hour,...,340,53.0,0.0,4.87,4.89,4.85,4.91,4.58,4.75,0.33
1,2024-09-23,city scrape,Athens Quality Apartments - Deluxe Apartment,Athens Quality Apartments - Deluxe apartment i...,Ampelokipi district is nice multinational and ...,Emmanouil,2009-09-08,"Athens, Greece",Athens Quality Apartments is a company started...,within an hour,...,350,82.0,0.0,4.83,4.85,4.85,4.90,4.80,4.75,0.56
2,2024-09-23,city scrape,Athens Quality Apartments - Studio,The Studio is an <br />-excellent located <br ...,Ampelokipi district is nice multinational and ...,Emmanouil,2009-09-08,"Athens, Greece",Athens Quality Apartments is a company started...,within an hour,...,341,107.0,0.0,4.85,4.92,4.93,4.97,4.79,4.78,0.73
3,2024-09-23,city scrape,"AQA-No2 1-bedroom, smart tv, fiber connection,","AQA No2 is 1-bedroom apartment (47m2), on the ...",Ampelokipi district is nice multinational and ...,Emmanouil,2009-09-08,"Athens, Greece",Athens Quality Apartments is a company started...,within an hour,...,350,36.0,0.0,4.83,4.97,4.91,4.89,4.82,4.82,0.21
4,2024-09-23,city scrape,"AQA-No7, Great mattress, high speed internet",THE MATTRESS - KING KOIL - Camden Luxury 160x2...,No disponible,Emmanouil,2009-09-08,"Athens, Greece",Athens Quality Apartments is a company started...,within an hour,...,358,25.0,0.0,4.84,4.88,4.96,4.96,4.75,4.71,0.17

Dataset: Hotel room

,last_scraped,source,name,description,neighborhood_overview,host_name,host_since,host_location,host_about,host_response_time,...,availability_365,number_of_reviews,number_of_reviews_l30d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
746,2024-09-23,previous scrape,Standard Double Room with private shower & Bal...,"My place is close to restaurants and dining, p...",No disponible,Konstantinos,2016-01-10,"Athens, Greece",No disponible,within an hour,...,320,1.0,0.0,4.00,5.00,5.00,5.00,5.00,5.00,0.01
825,2024-09-23,city scrape,Triple Room with private shower & Balcony,"My place is close to restaurants and dining, p...",No disponible,Konstantinos,2016-01-10,"Athens, Greece",No disponible,within an hour,...,328,1.0,0.0,5.00,5.00,5.00,5.00,5.00,5.00,0.03
1333,2024-09-23,city scrape,Exceptional Penthouse close to Acropolis by GHH,This exceptional Penthouse close to the Acropo...,A formerly low-profile neighborhood at the foo...,Golden Home Holidays,2015-10-20,"Athens, Greece","Find your own home in Greece, for holidays or ...",within an hour,...,135,84.0,1.0,4.64,4.73,4.73,4.94,4.95,4.69,1.03
1455,2024-09-23,city scrape,"Acropolis Grand Residence, Stunning Views","Located in a 1930’s neoclassical building, dir...",The residence is located at 12 Syggrou avenue ...,Vasileios,2017-01-31,"Athens, Greece",We are Bill & John two young entrepreneurs wit...,within an hour,...,292,184.0,1.0,4.98,4.97,4.97,4.98,4.99,4.95,2.33
1458,2024-09-23,city scrape,AcropolisView -Two Bedroom Apt by Meros,The apartment is located at the foothills of A...,Thissio is a traditional neighborhood in downt...,Meros,2015-05-06,"Athens, Greece","Hi, we are Meros team and we will be your host...",within an hour,...,74,116.0,5.0,4.77,4.84,4.88,4.79,4.92,4.79,1.48

Dataset: Private room

,last_scraped,source,name,description,neighborhood_overview,host_name,host_since,host_location,host_about,host_response_time,...,availability_365,number_of_reviews,number_of_reviews_l30d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
44,2024-09-23,city scrape,Lovely room in historic center,"relaxed, quiet area, next to all historic and ...",No disponible,Haris,2012-06-03,"Athens, Greece",Welcome in my profile on Airbnb! Infos about o...,within an hour,...,83,4.0,0.0,4.75,4.75,4.50,4.50,4.75,4.50,0.03
119,2024-09-23,city scrape,Room and private bathroom in Athens,Comfortable and quiet private bedroom with a k...,In my safe and easily accessible neighborhood ...,Nick,2014-04-06,"Athens, Greece","Hey , I'm Nick!",within an hour,...,29,42.9,5.0,4.92,4.97,4.91,4.96,4.87,4.93,3.09
123,2024-09-23,city scrape,Room with Balcony in Filopapos Hill,No disponible,No disponible,Sofia,2013-06-19,"Athens, Greece",I like traveling all over the world. It makes ...,a few days or more,...,362,15.0,0.0,4.73,4.87,5.00,5.00,4.73,4.80,0.11
131,2024-09-23,city scrape,Room with privet bathroom in Athens,Comfortable and quiet private bedroom with a p...,In my safe and easily accessible neighborhood ...,Nick,2014-04-06,"Athens, Greece","Hey , I'm Nick!",within an hour,...,52,42.9,3.0,4.93,4.95,4.96,4.95,4.87,4.94,3.08
149,2024-09-23,city scrape,Acropolis view-150 metres from Metro Monastiraki!,"My house is located in Monastiraki area, righ...",My neighborhood is the most charming area in A...,Makis,2014-05-06,"Athens, Greece",I am an actor and director. I like writing and...,within an hour,...,0,189.0,0.0,4.59,4.74,4.54,4.79,4.90,4.61,1.50

Dataset: Shared room

,last_scraped,source,name,description,neighborhood_overview,host_name,host_since,host_location,host_about,host_response_time,...,availability_365,number_of_reviews,number_of_reviews_l30d,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month
2091,2024-09-23,city scrape,Bedway Athens Hostel (Bed in female dormitory),"Bedway Athens Hostel is a brand new, modern Ho...",No disponible,Bedway Athens,2018-08-27,"Athens, Greece",No disponible,within a day,...,335,14.0,0.0,4.21,4.50,4.21,4.50,4.71,4.57,0.19
2125,2024-09-23,city scrape,Bedway Athens Hostel (Bed in mixed dormitory),"Bedway Athens Hostel is a brand new, modern Ho...",No disponible,Bedway Athens,2018-08-27,"Athens, Greece",No disponible,within a day,...,174,33.0,1.0,4.70,4.61,4.55,4.76,4.82,4.88,0.45
2133,2024-09-23,city scrape,Bedway Athens Hostel (Bed in mixed dormitory),"Bedway Athens Hostel is a brand new, modern Ho...",No disponible,Bedway Athens,2018-08-27,"Athens, Greece",No disponible,within a day,...,171,35.0,0.0,4.40,4.60,4.43,4.57,4.51,4.60,0.61
2134,2024-09-23,city scrape,Bedway Athens Hostel (Bed in mixed dormitory),"Bedway Athens Hostel is a brand new, modern Ho...",No disponible,Bedway Athens,2018-08-27,"Athens, Greece",No disponible,within a day,...,179,8.0,0.0,3.88,3.88,3.88,4.90,3.88,3.88,0.20
2135,2024-09-23,city scrape,Bedway Athens Hostel (Bed in female dormitory),"Bedway Athens Hostel is a brand new, modern Ho...",No disponible,Bedway Athens,2018-08-27,"Athens, Greece",No disponible,within a day,...,179,1.0,0.0,4.00,5.00,4.80,5.00,5.00,4.00,0.02

In [25]:
# Crear la carpeta del país si no existe
pais = 'México'
carpeta_pais = f"room_type_{pais}"
os.makedirs(carpeta_pais, exist_ok=True)

for room_type, data in room_type_datasets.items():
    # Limpiar el nombre del archivo (eliminar caracteres problemáticos y reemplazar espacios)
    sanitized_name = re.sub(r'[^\w\s]', '', room_type).replace(' ', '_')
    
    # Construir la ruta del archivo dentro de la carpeta del país
    filename = os.path.join(carpeta_pais, f"{sanitized_name}_{pais}.csv")
    
    # Guardar el dataset en un archivo CSV
    data.to_csv(filename, index=False)

    print(f"Archivo guardado en: {filename}")

Archivo guardado en: room_type_México\Entire_homeapt_México.csv
Archivo guardado en: room_type_México\Hotel_room_México.csv
Archivo guardado en: room_type_México\Private_room_México.csv
Archivo guardado en: room_type_México\Shared_room_México.csv